echo "~/.bash_aliases"
alias tig="tig --all"
alias gf="git fetch --all --prune --tags --force --prune-tags"
alias gc="git checkout"
alias gb="git branch"
alias gm="git merge"
alias gr="git reset --soft"
alias git-exec-pull-master="git-exec git fetch --all --prune --tags --force --prune-tags && git-exec git merge origin/master"
